export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'homeCenter',
    path: '/home',
    title: 'Home',
    requiresAuth: true,
    icon: 'carbon:user-avatar-filled-alt',
    componentPath: '/demo/userCenter/index.vue',
    id: 89,
    pid: null,
  },

  {
    name: 'dashboard',
    path: '/dashboard',
    title: 'Dashboard',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'dir',
    componentPath: null,
    id: 1,
    pid: null,
  },
  {
    name: 'Linux Dashboard',
    path: '/monitoring/linux',
    title: 'Linux Dashboard',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    pinTab: true,
    menuType: 'page',
    componentPath: '/monitoring/linux.vue',
    id: 2,
    pid: 1,
  },
  {
    name: 'Window Dashboard',
    path: '/monitoring/windows',
    title: 'Windows Dashboard',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    menuType: 'page',
    // componentPath: '/dashboard/monitor/index.vue',
    componentPath: '/monitoring/windows-m.vue',

    id: 3,
    pid: 1,
  },
  {
    name: 'Connection',
    path: '/list',
    title: 'Connection',
    requiresAuth: true,
    icon: 'icon-park-outline:application-one',
    menuType: 'dir',
    componentPath: null,
    id: 10,
    pid: null,
  },
  {
    name: 'Linux',
    path: '/infrastructure/server/linux',
    title: 'Linux ',
    requiresAuth: true,
    // icon: 'icon-park-outline:list-view',
    icon: 'icon-park-outline:list',

    componentPath: '/infrastructure/server/linux.vue',
    id: 11,
    pid: 10,
  },
  {
    name: 'Window',
    path: '/infrastructure/server/windows',
    title: 'Windows',
    requiresAuth: true,
    // icon: 'icon-park-outline:view-grid-list',
    icon: 'icon-park-outline:list',

    componentPath: '/infrastructure/server/windows.vue',
    id: 12,
    pid: 10,
  },
  {
    name: 'Gitlab',
    path: '/infrastructure/server/gitlab',
    title: 'Gitlab',
    requiresAuth: true,
    // icon: 'icon-park-outline:menu-fold',
    icon: 'icon-park-outline:list',

    componentPath: '/infrastructure/server/gitlab.vue',
    id: 44,
    pid: 10,
  },
  {
    name: 'Infrastructure Orchestration',
    path: '/multi',
    title: 'Infrastructure Orchestration',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    menuType: 'dir',
    componentPath: null,
    id: 4,
    pid: null,
  },

 
  {
    name: 'Kubernetes',
    path: '/multi/multi3',
    title: 'Kubernetes',
    requiresAuth: true,
    icon: 'icon-park-outline:anchor',
    menuType: 'dir',
    componentPath: null,
    id: 8,
    pid: 4,
  },
  {
    name: 'Cluster Overview',
    path: '/infra-orc/kubernetes/cluster',
    title: 'Cluster Overview',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/cluster.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Namespace',
    path: '/infra-orc/kubernetes/namespace',
    title: 'Namespace',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/namespace.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Pod',
    path: '/infra-orc/kubernetes/pods',
    title: 'Pods',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/pods.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Workload',
    path: '/infra-orc/kubernetes/workloads',
    title: 'Workloads',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/workloads.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Node',
    path: '/infra-orc/kubernetes/nodes',
    title: 'Nodes',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/nodes.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Alert',
    path: '/infra-orc/kubernetes/alerts',
    title: 'Alert',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/alerts.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Configuration',
    path: '/infra-orc/kubernetes/configuration',
    title: 'Configuration',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    componentPath: '/infra-orc/kubernetes/configuration.vue',
    id: 9,
    pid: 8,
  },
  {
    name: 'Docker',
    path: '/multi/multi2',
    title: 'Docker',
    requiresAuth: true,
    // icon: 'icon-park-outline:list',
    icon: 'icon-park-outline:list-view',

    menuType: 'page',
    componentPath: '/demo/multi/multi2/index.vue',
    id: 6,
    pid: 4,
  },
  
  {
    name: 'Application',
    path: '/error',
    title: 'Application',
    requiresAuth: true,
    icon: 'icon-park-outline:error-computer',
    menuType: 'dir',
    componentPath: null,
    id: 31,
    pid: null,
  },
  {
    name: 'APM Dashbaord',
    path: '/error/403',
    title: 'APM Dashbaord',
    requiresAuth: true,
    icon: 'icon-park-outline:list',
    order: 3,
    componentPath: '/error/403/index.vue',
    id: 32,
    pid: 31,
  },
  {
    name: 'Alert&IRM',
    path: '/demo',
    title: 'Alert and IRM',
    requiresAuth: true,
    icon: 'icon-park-outline:application-one',
    menuType: 'dir',
    componentPath: null,
    id: 13,
    pid: null,
  },
  {
    name: 'Oncall',
    path: '/demo/fetch',
    title: 'Oncall',
    requiresAuth: true,
    icon: 'icon-park-outline:international',
    componentPath: '/demo/fetch/index.vue',
    id: 5,
    pid: 13,
  },
  {
    name: 'Alerting',
    path: '/demo/echarts',
    title: 'Alerting',
    requiresAuth: true,
    icon: 'icon-park-outline:chart-proportion',
    componentPath: '/demo/echarts/index.vue',
    id: 15,
    pid: 13,
  },
  // {
  //   name: 'map',
  //   path: '/demo/map',
  //   title: 'Map',
  //   requiresAuth: true,
  //   icon: 'carbon:map',
  //   keepAlive: true,
  //   componentPath: '/demo/map/index.vue',
  //   id: 17,
  //   pid: 13,
  // },
  // {
  //   name: 'editor',
  //   path: '/demo/editor',
  //   title: 'Editor',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:editor',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 18,
  //   pid: 13,
  // },
  // {
  //   name: 'editorMd',
  //   path: '/demo/editor/md',
  //   title: 'Markdown',
  //   requiresAuth: true,
  //   icon: 'ri:markdown-line',
  //   componentPath: '/demo/editor/md/index.vue',
  //   id: 19,
  //   pid: 18,
  // },
  // {
  //   name: 'editorRich',
  //   path: '/demo/editor/rich',
  //   title: 'Rich Text Editor',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:edit-one',
  //   componentPath: '/demo/editor/rich/index.vue',
  //   id: 20,
  //   pid: 18,
  // },
  // {
  //   name: 'clipboard',
  //   path: '/demo/clipboard',
  //   title: 'Clipboard',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:clipboard',
  //   componentPath: '/demo/clipboard/index.vue',
  //   id: 21,
  //   pid: 13,
  // },

  // {
  //   name: 'icons',
  //   path: '/demo/icons',
  //   title: 'Icons',
  //   requiresAuth: true,
  //   icon: 'local:cool',
  //   componentPath: '/demo/icons/index.vue',
  //   id: 22,
  //   pid: 13,
  // },
  // {
  //   name: 'QRCode',
  //   path: '/demo/QRCode',
  //   title: 'QR Code',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:two-dimensional-code',
  //   componentPath: '/demo/QRCode/index.vue',
  //   id: 23,
  //   pid: 13,
  // },

  // Iframe
  // {
  //   name: 'documents',
  //   path: '/documents',
  //   title: 'External Documents',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:file-doc',
  //   menuType: 'dir',
  //   componentPath: null,
  //   id: 24,
  //   pid: null,
  // },
  // {
  //   name: 'documentsVue',
  //   path: '/documents/vue',
  //   title: 'Vue',
  //   requiresAuth: true,
  //   icon: 'logos:vue',
  //   componentPath: '/demo/documents/vue/index.vue',
  //   id: 25,
  //   pid: 24,
  // },
  // {
  //   name: 'documentsVite',
  //   path: '/documents/vite',
  //   title: 'Vite',
  //   requiresAuth: true,
  //   icon: 'logos:vitejs',
  //   componentPath: '/demo/documents/vite/index.vue',
  //   id: 26,
  //   pid: 24,
  // },
  // {
  //   name: 'documentsVueuse',
  //   path: '/documents/vueuse',
  //   title: 'VueUse (External Link)',
  //   requiresAuth: true,
  //   icon: 'logos:vueuse',
  //   href: 'https://vueuse.org/guide/',
  //   componentPath: 'null',
  //   id: 27,
  //   pid: 24,
  // },
  {
    name: 'datasource',
    path: '/permission',
    title: 'Datasource',
    requiresAuth: true,
    icon: 'icon-park-outline:people-safe',
    // menuType: 'dir',
    componentPath: '/demo/permission/permission/index.vue',
    id: 28,
    pid: null,
  },
  // {
  //   name: 'about',
  //   path: '/about',
  //   title: '关于',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:info',
  //   componentPath: '/demo/about/index.vue',
  //   id: 40,
  //   pid: null,
  // },
  // {
  //   name: 'postgres',
  //   path: '/permission/permission',
  //   title: 'PostgresSQL',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:right-user',
  //   componentPath: '/demo/permission/permission/index.vue',
  //   id: 29,
  //   pid: 28,
  // },
  // {
  //   name: 'userCenter',
  //   path: '/userCenter',
  //   title: '个人中心',
  //   requiresAuth: true,
  //   icon: 'carbon:user-avatar-filled-alt',
  //   componentPath: '/demo/userCenter/demo.vue',
  //   id: 39,
  //   pid: null,
  // },
  // {
  //   name: 'justSuper',
  //   path: '/permission/justSuper',
  //   title: 'Visible to Super',
  //   requiresAuth: true,
  //   roles: ['super'],
  //   icon: 'icon-park-outline:wrong-user',
  //   componentPath: '/demo/permission/justSuper/index.vue',
  //   id: 30,
  //   pid: 28,
  // },
  
  // {
  //   name: 'demo404',
  //   path: '/error/404',
  //   title: '404',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:error',
  //   order: 2,
  //   componentPath: '/error/404/index.vue',
  //   id: 33,
  //   pid: 31,
  // },
  // {
  //   name: 'demo500',
  //   path: '/error/500',
  //   title: '500',
  //   requiresAuth: true,
  //   icon: 'carbon:data-error',
  //   order: 1,
  //   componentPath: '/error/500/index.vue',
  //   id: 34,
  //   pid: 31,
  // },
  {
    name: 'Adiministration',
    path: '/setting',
    title: 'Adiministration',
    requiresAuth: true,
    icon: 'icon-park-outline:setting',
    menuType: 'dir',
    componentPath: null,
    id: 35,
    pid: null,
  },
  {
    name: 'userSetting',
    path: '/setting/account',
    title: 'User Settings',
    requiresAuth: true,
    icon: 'icon-park-outline:every-user',
    componentPath: '/setting/account/index.vue',
    id: 36,
    pid: 35,
  },
  {
    name: 'generalSetting',
    path: '/setting/dictionary',
    title: 'General Settings',
    requiresAuth: true,
    icon: 'icon-park-outline:book-one',
    componentPath: '/setting/dictionary/index.vue',
    id: 37,
    pid: 35,
  },
  // {
  //   name: 'menuSetting',
  //   path: '/setting/menu',
  //   title: 'Menu Settings',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:application-menu',
  //   componentPath: '/setting/menu/index.vue',
  //   id: 38,
  //   pid: 35,
  // },
  // {
  //   name: 'userCenter',
  //   path: '/userCenter',
  //   title: 'User Center',
  //   requiresAuth: true,
  //   icon: 'carbon:user-avatar-filled-alt',
  //   componentPath: '/demo/userCenter/index.vue',
  //   id: 39,
  //   pid: null,
  // },
  // {
  //   name: 'about',
  //   path: '/about',
  //   title: 'About',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:info',
  //   componentPath: '/demo/about/index.vue',
  //   id: 40,
  //   pid: null,
  // },
  // {
  //   name: 'cascader',
  //   path: '/demo/cascader',
  //   title: 'Province-City-District Linkage',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:add-subset',
  //   componentPath: '/demo/cascader/index.vue',
  //   id: 41,
  //   pid: 13,
  // },

  // {
  //   name: 'dict',
  //   path: '/demo/dict',
  //   title: 'Dictionary Example',
  //   requiresAuth: true,
  //   icon: 'icon-park-outline:book-one',
  //   componentPath: '/demo/dict/index.vue',
  //   id: 43,
  //   pid: 13,
  // },

]
