# Generated by Django 4.2.9 on 2024-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0002_adgrouproleassignment_ldapgroup_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('viewer', 'Viewer'), ('editor', 'Editor'), ('maintner', 'Maintner'), ('Admin', 'Admin'), ('Standard', 'Standard')], max_length=15),
        ),
    ]
