# Generated by Django 3.2.25 on 2024-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('roles', models.JSONField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
