# Generated by Django 3.2.25 on 2024-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0005_keycloakuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycloakuser',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keycloakuser',
            name='roles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
