# Generated by Django 3.2.25 on 2024-11-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0006_auto_20241114_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keycloakuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='keycloakuser',
            name='last_login',
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255, unique=True)),
                ('ip_port', models.CharField(max_length=150, unique=True)),
                ('agent_name', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Gitlab', 'Gitlab')], max_length=150)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deleted', 'Deleted')], max_length=150)),
                ('access_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth_app.keycloakuser', verbose_name='Access Token')),
            ],
        ),
    ]
