# Generated by Django 3.2.25 on 2024-11-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0008_alter_agent_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='access_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth_app.keycloakuser', verbose_name='Access Token'),
        ),
    ]
