# Generated by Django 3.2.25 on 2024-11-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0009_alter_agent_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='access_token',
        ),
        migrations.AddField(
            model_name='agent',
            name='keycloak_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth_app.keycloakuser', verbose_name='Keycloak User'),
        ),
    ]
