# Generated by Django 3.2.25 on 2024-11-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth_app', '0010_auto_20241115_0629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADGroupRoleAssignment',
        ),
        migrations.AlterUniqueTogether(
            name='ldapgroupmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ldapgroupmember',
            name='group',
        ),
        migrations.DeleteModel(
            name='LDAPGroup',
        ),
        migrations.DeleteModel(
            name='LDAPGroupMember',
        ),
    ]
