# Generated by Django 4.2.8 on 2023-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule__api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
